name: Lint and test

on:
  push:
    branches:
      - master
  pull_request:

env:
  NODE_VERSION: '16'

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 7
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint js
        run: npm run lint:js

      - name: Lint hbs
        run: npm run lint:hbs

      - name: Run tests
        run: npm run test:ember
